# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palantir < Formula
  desc "TUI for AWS CloudFormation & ECS exploration with port forwarding"
  homepage "https://github.com/erdemcemal/palantir"
  version "0.4.1"
  license "MIT"

  depends_on "awscli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.1/palantir_0.4.1_darwin_amd64.tar.gz"
      sha256 "05f715d550f4b5442bd78c93c243ca727e4aab9a721fe96b632c74b76b20d85c"

      def install
        bin.install "palantir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.1/palantir_0.4.1_darwin_arm64.tar.gz"
      sha256 "0fc451024032e07c90474c5caed1d97d44b41700143cfd8bec3d932e4e2e19f7"

      def install
        bin.install "palantir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.1/palantir_0.4.1_linux_amd64.tar.gz"
      sha256 "711d2298bd342365ee120c55c1992218a3e8073e974e9da0fe38c6948bbc1160"
      def install
        bin.install "palantir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.1/palantir_0.4.1_linux_arm64.tar.gz"
      sha256 "8b842d279763be0fcf675f4d1432da6430cf68c70e24578ae4bc46e2741d3c3a"
      def install
        bin.install "palantir"
      end
    end
  end

  test do
    system "#{bin}/palantir", "--version"
  end
end
