# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palantir < Formula
  desc "TUI for AWS CloudFormation & ECS exploration with port forwarding"
  homepage "https://github.com/erdemcemal/palantir"
  version "0.4.0"
  license "MIT"

  depends_on "awscli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.0/palantir_0.4.0_darwin_amd64.tar.gz"
      sha256 "e8cd78b209c9116e45cdab93018f01328c407f9900a3aa7d74b5a5c40b54f599"

      def install
        bin.install "palantir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.0/palantir_0.4.0_darwin_arm64.tar.gz"
      sha256 "950e778ef2bbe5451c6256f665b59ca3946fd4a2a22230638d06897df917ff33"

      def install
        bin.install "palantir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.0/palantir_0.4.0_linux_amd64.tar.gz"
      sha256 "64c274c73e768d8741fd4a91d36d1d835872f532dfca922e47a0bcff3349e843"
      def install
        bin.install "palantir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/palantir/releases/download/v0.4.0/palantir_0.4.0_linux_arm64.tar.gz"
      sha256 "9b608e48adf726a832ae16d544823696e0fffbdf1c048240ea36a1bb4c0b2d2a"
      def install
        bin.install "palantir"
      end
    end
  end

  test do
    system "#{bin}/palantir", "--version"
  end
end
