# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaws < Formula
  desc "TUI for AWS CloudFormation & ECS exploration with port forwarding"
  homepage "https://github.com/erdemcemal/vaws"
  version "1.5.0"
  license "MIT"

  depends_on "awscli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.5.0/vaws_1.5.0_darwin_amd64.tar.gz"
      sha256 "34b9672ce6512cdc3eafb79cc40e5c9fcaa23192649bb09a164f89befe4692d4"

      def install
        bin.install "vaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.5.0/vaws_1.5.0_darwin_arm64.tar.gz"
      sha256 "63618e578adb4ec9d05b57c7c1d6d5527eecab35f79364b26fedca996f85e1f3"

      def install
        bin.install "vaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.5.0/vaws_1.5.0_linux_amd64.tar.gz"
      sha256 "7356aed391fdd6d1bd7656c05548f27ac395e9f42e4bca8cabdd20853b71ad56"
      def install
        bin.install "vaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.5.0/vaws_1.5.0_linux_arm64.tar.gz"
      sha256 "eaf285c435ccc926f758d3bd749942a57bcca81909307bad5a0a6432c15f05a7"
      def install
        bin.install "vaws"
      end
    end
  end

  test do
    system "#{bin}/vaws", "--version"
  end
end
