# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaws < Formula
  desc "TUI for AWS CloudFormation & ECS exploration with port forwarding"
  homepage "https://github.com/erdemcemal/vaws"
  version "1.1.2"
  license "MIT"

  depends_on "awscli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.1.2/vaws_1.1.2_darwin_amd64.tar.gz"
      sha256 "d7c47830174a3f1f8d76229adbcd82f474a62ded1ff3f20a06cbf8f0d737173a"

      def install
        bin.install "vaws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.1.2/vaws_1.1.2_darwin_arm64.tar.gz"
      sha256 "4d3a16da41c908cfb4a8d8b24998e0680aaea79a52e23b01b1bce0a320c0c4c7"

      def install
        bin.install "vaws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.1.2/vaws_1.1.2_linux_amd64.tar.gz"
      sha256 "c20b791c9ea069fe8342b50e0e746778cd29c3af300045a0677041be081bfc30"
      def install
        bin.install "vaws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdemcemal/vaws/releases/download/v1.1.2/vaws_1.1.2_linux_arm64.tar.gz"
      sha256 "93c09e0bd371996ba1c8ab3ae6acd1d018f23c0672ccb9012fb56d4edafa3380"
      def install
        bin.install "vaws"
      end
    end
  end

  test do
    system "#{bin}/vaws", "--version"
  end
end
